### ISSUE TITLE
VPN Verbindungen aktivieren/deaktivieren/anzeigen

### ISSUE THREAD

**Issue by JuergenOrth** [MarcusRoeckrath/fbtr64toolbox#1]
Ist es möglich mit diesem Toolset VPN Verbindungen zu (de-) aktivieren und anzuzeigen? Habe da nichts in der Doku oder den ladbaren XML files finden können.

**Comment by MarcusRoeckrath** [comment]
Hallo Jürgen,

ich finde in den TR64-Funktionen, wie sie AVM in der Doku auf https://avm.de/service/schnittstellen/ beschreibt, keine entsprechende Funktion.

Der Begriff VPN kommt fast nur im Dokument https://avm.de/fileadmin/user_upload/Global/Service/Schnittstellen/x_appsetup.pdf vor und zwar als Funktionen SetAppVPN und SetAppVPNwithPFS, mit denen man wohl neue ipsec-VPN-Verbindungen anlegen kann.

Die Funktion X_AVM-DE_GetSpecificHostEntryByIp beschrieben in https://avm.de/fileadmin/user_upload/Global/Service/Schnittstellen/hostsSCPD.pdf liefert einen boolean-Wert NewX_AVM-DE_VPN für den mittels IP angegebenen lokalen Host, was immer AVM damit aussagen möchte.

fbtr64toolbox.sh hostbyipinfo <ip>

zeigt dieses Wert an.

Marcus
