### ISSUE TITLE
Dockerfile

### ISSUE THREAD

**Issue by caco3** [MarcusRoeckrath/fbtr64toolbox#8]
I wanted to run the new script on my Synology NAS. Since it fails to run natively, I build a docker image.
Here is the Dockerfile I created in case somebody else wants to use it:
```dockerfile
FROM debian:latest

RUN apt-get update && \
    DEBIAN_FRONTEND=noninteractive apt-get -qq -y install \
    wget bzip2 bc curl dos2unix ksh xmlstarlet

RUN wget https://www.pack-eis.de/dl.php?l=64373/fbtr64toolbox.tar.bz2 -O fbtr64toolbox.tar.bz2
RUN wget https://www.pack-eis.de/dl.php?l=65204/eisfair-base.tar.bz2 -O eisfair-base.tar.bz2

RUN tar -xf fbtr64toolbox.tar.bz2
RUN tar -xf eisfair-base.tar.bz2
```

To build it: `docker build -t fbtr64toolbox .`
To run it the first time and create the template config file:
```sh
docker run -it --rm -v $(pwd)/config:/root --name fbtr64toolbox fbtr64toolbox bash /usr/bin/fbtr64toolbox.sh writeconfig
```

Then adjust the config parameters in `./config/.fbtr64toolbox`.

To use it afterwards, call it through docker as if you would call it directly, eg:
```sh
> docker run -it --rm -v $(pwd)/config:/root --name fbtr64toolbox fbtr64toolbox bash /usr/bin/fbtr64toolbox.sh show
Port forwardings (FRITZ!Box 5530 Fiber Release 257.07.81@192.168.1.1)
Port forwardings set by authorized users
Idx Act Description               Host IP:Port        Pro Client IP:Port        
  [..]
 10 yes LetsEncrypt               0.0.0.0:80          TCP 192.168.1.2:80       

Port forwardings set by any user/device via upnp
```

### Note
The script will always throw an error, but seems to work correctly anyway:
```sh
/var/install/include/eislib: line 41: /var/install/include/sectionslib: No such file or directory
```

**Comment by MarcusRoeckrath** [comment]
Hello,

Am Mittwoch, 28. August 2024, 15:17:52 schrieb CaCO3:

> I wanted to run the new script on my Synology NAS. Since it fails to run
> natively, I build a docker image. Here is the Dockerfile I created in case
> somebody else wants to use it: ```dockerfile

Good idea.

> FROM debian:latest
> 
> RUN apt-get update && \
>     DEBIAN_FRONTEND=noninteractive apt-get -qq -y install \
>     wget bzip2 bc curl dos2unix ksh xmlstarlet
> 
> RUN wget https://www.pack-eis.de/dl.php?l=64373/fbtr64toolbox.tar.bz2 -O
> fbtr64toolbox.tar.bz2 RUN wget
> https://www.pack-eis.de/dl.php?l=65204/eisfair-base.tar.bz2 -O
> eisfair-base.tar.bz2
> 
> RUN tar -xf fbtr64toolbox.tar.bz2
> RUN tar -xf eisfair-base.tar.bz2

Why not using the archive from github because these contains all needed parts 
for the use of the script on linux distros other than eisfair?

https://github.com/MarcusRoeckrath/fbtr64toolbox/raw/main/fbtr64toolbox.tar.bz2

eisfair-base is not needed because one special eisfair file from eisfair-base 
is included in the archive on github.

-- 
Gruß Marcus

**Comment by MarcusRoeckrath** [comment]
Hi,

Am Donnerstag, 29. August 2024, 12:17:41 schrieb CaCO3:

> > Why not using the archive from github because these contains all needed
> > parts
> for the use of the script on linux distros other than eisfair?
> 
> That's a good point. I initially took the script from your website

Thats not my website, it's the website and package download server of the 
german linux server distribution "eisfair" where I'm part of the core team.

> and did not expect that the Github version is different.

The functionalty in both archives is the same, it's exaclty byte by byte the 
same script.

The eisfair package contains parts only needed on eisfair like menu files for 
the distros menu structure, an installation and update routine, ...which has 
to be part of every installation package on eisfair.

I created the package archiv and the github for the use of fbtr64toolbox on 
any other distro on request of the german it magazine c't when mentioning my 
project in an article about fritzbox and tr64 last year.
 
Have fun with my script and ask me, possibly by pm, when you have questions or 
suggestions.

-- 
Gruß Marcus

**Comment by MarcusRoeckrath** [comment]
Hi,

> The script will always throw an error, but seems to work correctly anyway:
> /var/install/include/eislib: line 41: /var/install/include/sectionslib: No such file or directory

That's because you have used the eisfair package in which eislib depends on sectionslib.

The github archive contains an modified eislib only containing those code parts which are needed by fbtr64toolbox.

This error should not appear using the package from github.

Marcus
